import Head from 'next/head'
import Image from 'next/image'
import Form from '@/components/form'
import Header from "@/components/header"



export default function Home() {
  return (
    <>
      <Head>
        <title>Invitation Card</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="ml-5">
        <Header />
        <div className = "w-2/5">
          <Form />
        </div>
      </main>
    </>
  )
}
